name: Release

on:
  release:
    types: [published]

jobs:

  PyPi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: python3 -m pip install --upgrade pip setuptools wheel twine
      - name: Build3 dist packages
        run: python setup.py sdist bdist_wheel
      - name: Upload packages
        run: python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
